par(mfrow=c(2,2))
x<-seq(-3,4,length=2000)
plot(x,dnorm(x),axes=F,type='l',xlab='(a)',ylab='')
abline(h=0)
lines(x,dnorm(x,.5,1))

x<-seq(-3,4,length=2000)
plot(x,dnorm(x,-.5,.5),axes=F,type='l',xlab='(b)',ylab='')
abline(h=0)
lines(x,dnorm(x,1,1))

x<-seq(-1,10,length=2000)
plot(x,dgamma(x,2),axes=F,type='l',xlab='(c)',ylab='')
abline(h=0)
lines(x+1,dgamma(x,2))

x<-seq(-6,10,length=2000)
plot(x,dgamma(x,2),axes=F,type='l',xlab='(d)',ylab='')
abline(h=0)
lines(x,dnorm(x,-1,1.5))